AWSTemplateFormatVersion: 2010-09-09
Description: Deploy the S3 Service Catalog Product
Parameters:
  ProvisionedArtifactName:
    Type: String
    Description: The provisioned artifact name/ current product version.
  DevelopmentTeam:
    Type: AWS::SSM::Parameter::Value<String>
    Description: SSM Parameter for team owning the created resources.
    Default: /AdminParams/Team/Name
    AllowedValues:
      - /AdminParams/Team/Name
  DevelopmentEnvironment:
    Type: AWS::SSM::Parameter::Value<String>
    Description: SSM Parameter for development environment this will live in.
    Default: /AdminParams/Team/Environment
    AllowedValues:
      - /AdminParams/Team/Environment
Resources:
  Bucket:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: S3
      ProvisioningArtifactName: !Ref ProvisionedArtifactName
      ProvisionedProductName: test-apigateway-s3-for-lambda
      ProvisioningParameters:
        # required parameter
        - Key: BucketNameSuffix
          Value: test-apigateway-s3-for-lambda-bucket
      Tags:
        - Key: doNotShutDown
          Value: true