template_path: SC_APIGateway.yaml
parameters:
  ProvisionedArtifactName: {{ SC_APIGateway }}
  ApiName: "qs-example-public-api-with-iam"
  ApiDescription: "This is quickstart public API"
  ApiSpec: "quickstart/public-apig.yaml"
  S3BucketName: "gd-revenueapi-dev-private-test-apigateway-s3-for-lambda-bucket"