AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

  # Api:
  #   Cors:
  #     AllowMethods: "'*'"
  #     AllowHeaders: "'*'"
  #     AllowOrigin: "'*'"

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/sourceSystems/{sourceSystemId}/orders
            Method: post
            RestApiId: !Ref Api
            # RequestModel: 
            #   Model: Order
            #   Required: true
      #   ApiEvent2:
      #     Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      #     Properties:
      #       Path: /v1/sourceSystems/{sourceSystemId}/orders/{orderId}
      #       Method: post
      #       RestApiId: !Ref Api

  HelloWorldFunctionIamRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - 
            Effect: Allow
            Principal: 
              Service: 
                - lambda.amazonaws.com
            Action: 
              - sts:AssumeRole
      Policies:
        -
          PolicyName: HelloWorldPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action: 
                  - cloudwatch:*
                  - logs:*
                Resource: "*"

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: s3://ascending-devops/spec/Sales_Order_Schema_Revised.yaml
      # Models: 
      #   Order:
      #     title: Model
      #     required:
      #       - orderId
      #       - customerId
      #       - itemLineCount
      #       - orderLegalEntityId
      #       - createdAtLocal
      #       - totalResourceAmount
      #       - totalFees
      #       - totalTaxAmount
      #       - totalPaymentAmount
      #       - payments
      #       - orderItems
      #       - billToCountry
      #     type: object
      #     properties:
      #       orderId:
      #         maxLength: 36
      #         minLength: 1
      #         type: string
      #         description: Source System Order Id Value.
      #       customerId:
      #         type: string
      #         format: uuid
      #         description: An identifier for a customer
      #       itemLineCount:
      #         type: integer
      #         description: Total Count of Sales Order Items included in this order..
      #         format: int
      #       orderLegalEntityId:
      #         type: string
      #         # allOf:
      #         #   - $ref: "#/components/schemas/ARLegalEntities"
      #         description: >-
      #           Legal Entity/Accounting Entity where the Accounts Receivable has to be Booked. List of Legal Entities will be Provided.
      #       createdAtLocal:
      #         type: string
      #         description: >-
      #           Dates MUST be represented as ISO 8601 formatted strings. Order Created Date locally with respect to Statutory Reporting Date
      #         format: date-time
      #       totalResourceAmount:
      #         type: string
      #         # allOf:
      #         #   - $ref: "#/components/schemas/ResourceAmount"
      #         description: >-
      #           Control Value: The sum of all Resource Amounts.
      #       totalFees:
      #         type: string
      #         # allOf:
      #         #   - $ref: "#/components/schemas/Amount"
      #         description: >-
      #           Control Value:  The Sum of Fees
      #       totalTaxAmount:
      #         type: string
      #         # allOf:
      #         #   - $ref: "#/components/schemas/Amount"
      #         description: >-
      #           Control Value: The sum of all Tax Amounts if there are taxes associated to resources.
      #       totalPaymentAmount:
      #         type: string
      #         # allOf:
      #         #   - $ref: "#/components/schemas/Amount"
      #         description: >-
      #           Control Value: The sum of all payment amounts
      #       billToCountry:
      #         type: string
      #         format: iso-country-code
      #         pattern: ^[A-Z][A-Z]$
      #         default: US
      #         description: Two-letter ISO country code. The customer billing country.
      #       orderItems:
      #         type: array
      #         items:
      #           type: object
      #           properties:
      #             Id:
      #               type: string
      #         # items:
      #         #   $ref: "#/components/schemas/OrderItem"
      #         # description: De-bundles sales order item resources
      #       payments:
      #         type: array
      #         items:
      #           type: string
      #           # properties:
      #           #   Id:
      #           #     type: string
      #         # items:
      #         #   $ref: "#/components/schemas/Payment"
      #         description: A collection of payments for the sales order (MerchantAccountKey, AmountPaid)
          # additionalProperties: false
          # description: Sales Order Object

  # RequestValidator:
  #   Type: AWS::ApiGateway::RequestValidator
  #   Properties:
  #     RestApiId: !Ref Api
  #     ValidateRequestBody: true